### User sign up end point
POST http://localhost:3001/v1/user
Content-Type: application/json

 {
  "name": "John Doe",
  "company": "XYZ Corporation",
  "address": "123 Main St, City, Country",
  "phone": 1234567890,
  "email": "sdfasd@example.com",
  "password": "securepassword"
}

### User sign in end point
POST http://localhost:3001/v1/user/login
Content-Type: application/json

 {
   "email": "sdfasd@example.com",
  "password": "securepassword"
}