### User sign up end point
POST http://localhost:3001/v1/user
Content-Type: application/json

 {
  "name": "John Doe",
  "company": "XYZ Corporation",
  "address": "123 Main St, City, Country",
  "phone": 1234567890,
  "email": "sdfasd@example.com",
  "password": "securepassword"
}

### User sign in end point
POST http://localhost:3001/v1/user/login
Content-Type: application/json

 {
  "email": "sdfasd@example.com",
  "password": "securepassword"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkZmFzZEBleGFtcGxlLmNvbSIsImlhdCI6MTcwMDY4ODU0MywiZXhwIjoxNzAwNzc0OTQzfQ.6h3RUyXWgrUlDOGuxJWfQphk65E9_9Jb7xQWxW8SNyk